#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticiasDataAccess.Noticia.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TestICv6")]
	public partial class NoticiaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public NoticiaDataContext() : 
				base(global::NoticiasDataAccess.Properties.Settings.Default.TestICv6ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NoticiaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NoticiaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NoticiaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NoticiaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Noticias_Consultar_Todas")]
		public ISingleResult<Noticias_Consultar_TodasResult> Noticias_Consultar_Todas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Noticias_Consultar_TodasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Noticias_Insertar")]
		public int Noticias_Insertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="NVarChar(100)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cuerpo", DbType="NVarChar(MAX)")] string cuerpo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaCreacion", DbType="DateTime")] System.Nullable<System.DateTime> fechaCreacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Imagen", DbType="VarBinary(MAX)")] System.Data.Linq.Binary imagen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), titulo, cuerpo, fechaCreacion, imagen);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class Noticias_Consultar_TodasResult
	{
		
		private int _NoticiaId;
		
		private string _Titulo;
		
		private string _Cuerpo;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private System.Data.Linq.Binary _Imagen;
		
		public Noticias_Consultar_TodasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticiaId", DbType="Int NOT NULL")]
		public int NoticiaId
		{
			get
			{
				return this._NoticiaId;
			}
			set
			{
				if ((this._NoticiaId != value))
				{
					this._NoticiaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(100)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuerpo", DbType="NVarChar(MAX)")]
		public string Cuerpo
		{
			get
			{
				return this._Cuerpo;
			}
			set
			{
				if ((this._Cuerpo != value))
				{
					this._Cuerpo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this._Imagen = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
